name: Feature Request
description: Suggest a new feature for this mod
title: 'Feature Request: '
labels: ['enhancement']
projects: ['B1rtek/Geode-GDDLIntegration']
assignees:
  - B1rtek
body:
  - type: textarea
    id: problem-related
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is, for example *I'm always frustrated when [...]*
      placeholder: 'Last time I tried to do something in this mod I managed to burn my soup'
    validations:
      required: false
  - type: textarea
    id: preferred-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
      placeholder: 'The mod should warn the user every 2 to 3 minutes reminding them that they''re cooking soup'
    validations:
      required: true
  - type: textarea
    id: alternative-solutions
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: 'Maybe I should just pay attention to my soup a bit more'
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: 'I think that cooking soup is hard...'
    validations:
      required: false
  - type: checkboxes
    id: latest-version-check
    attributes:
      label: I am running the latest version of the mod
      description: Make sure to check that! If you aren't add information about that in Additional context below
      options:
        - label: Yes, I am
          required: false